{{- if and (.Values.deployment.podDisruptionBudget) (.Values.deployment.podDisruptionBudget.enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "webhook.fullname" . }}
  namespace: {{ include "webhook.namespace" . }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "webhook.selectorLabels" . | nindent 6 }}
  {{- if .Values.deployment.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.deployment.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.deployment.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.deployment.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
